CREATE DATABASE snptx WITH ENCODING 'utf8';

-- CREATE USER 'web'@'localhost';
-- GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE ON snptx.* TO 'web'@'localhost';
-- ALTER USER 'web'@'localhost' IDENTIFIED BY 'pass';

-- CREATE USER 'web'@'192.168.0.170';
-- GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE ON snptx.* TO 'web'@'192.168.0.170';
-- ALTER USER 'web'@'192.168.0.170' IDENTIFIED BY 'pass';
