# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: '3.9' # optional since Compose v1.27.0

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: db
    image: cockroachdb/cockroach:v24.2.1
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      shared-network:
    ports:
    - published: 8080
      target: 8080
    - published: 26257
      target: 26257
    volumes:
    - crdb_data:/cockroach/cockroach-data

  snptx:
    container_name: snptx
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMIN_DB_DISABLE_TLS: '1'
      ADMIN_DB_HOST: 'db:26257'
      SNPTX_DB_DISABLE_TLS: '1'
      SNPTX_DB_HOST: 'db:26257'
      SNPTX_DB_NAME: postgres
      SNPTX_DB_PASSWORD: postgres
      SNPTX_DB_USER: admin
      SNPTX_WEB_SESSION_SECRET: ${SESSION_SECRET}
    image: tullo/snptx-amd64:0.1.0
    networks:
      shared-network: null
    ports:
    - published: 4200
      target: 4200
    user: '100000'

volumes:
  crdb_data: {}
