version: '3'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: web_db
    networks:
      - shared-network
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
