// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Snippet struct {
	SnippetID   string
	Title       pgtype.Text
	Content     pgtype.Text
	DateExpires pgtype.Timestamptz
	DateCreated pgtype.Timestamptz
	DateUpdated pgtype.Timestamptz
}

type User struct {
	UserID       string
	Name         pgtype.Text
	Email        pgtype.Text
	Active       pgtype.Bool
	Roles        []string
	PasswordHash pgtype.Text
	DateCreated  pgtype.Timestamptz
	DateUpdated  pgtype.Timestamptz
}
